name: Gradle Build

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master

jobs:
  build:
    name: 使用 Gradle 构建
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 缓存 Gradle 包
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: 设置 JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: 设置 JAVA_HOME
      run: echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV

    - name: 验证 JAVA_HOME
      run: echo $JAVA_HOME

    - name: 设置项目
      run: ./gradlew setup

    - name: 构建项目
      run: ./gradlew iris

    - name: 检查 Iris 目录
      run: ls -R Iris || echo "Iris 目录不存在"

    - name: 列出构建输出
      run: ls -R Iris/build || echo "Iris/build 目录不存在"
