name: Gradle Build

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build with Gradle
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Set JAVA_HOME
      run: echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV

    - name: Verify JAVA_HOME
      run: echo $JAVA_HOME

    - name: Setup project
      run: ./gradlew setup
      
    - name: Build project
      run: ./gradlew iris

    - name: List build outputs
      run: ls -R Iris/build
