name: Gradle Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: 使用 Gradle 构建
    runs-on: macos-14

    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 缓存 Gradle 包和 Maven 本地仓库
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.m2/repository
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          ${{ runner.os }}-maven-

    - name: 设置 JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: 设置 JAVA_HOME
      run: echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV

    - name: 验证 JAVA_HOME
      run: echo $JAVA_HOME

    - name: 设置项目
      run: ./gradlew setup --parallel --max-workers=3

    - name: 构建项目
      run: ./gradlew build --parallel --max-workers=3 --info --stacktrace

    - name: 运行 iris 任务
      run: ./gradlew iris --parallel --max-workers=3 --info --stacktrace

    - name: 列出当前目录内容
      run: ls -R . || echo "当前目录不存在"

    - name: 列出 Iris 目录内容
      run: ls -R Iris || echo "Iris 目录不存在"

    - name: 列出构建输出
      run: ls -R Iris/build || echo "Iris/build 目录不存在"
